# Generated by Django 4.0.4 on 2022-05-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='status',
            new_name='postar',
        ),
    ]
